import { IColumn } from '@/app/shared/table-primeng/table-primeng.component'
// export const columns = docenteTemplateColumns.
export const docentePlatformTemplateColumns: IColumn[] = [
    {
        type: 'text',
        width: '5rem',
        field: 'cTipoIdentId',
        header: 'Tipo de documento',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'cPersDocumento',
        header: 'Número de documento',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'cPersPaterno',
        header: 'Apellido paterno',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'cPersMaterno',
        header: 'Apellido materno',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'cPersNombre',
        header: 'Nombres',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'cPersSexo',
        header: 'Sexo',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'iHorasLabora',
        header: 'Horas laborales',
        text_header: 'center',
        text: 'center',
    },
]

export const resultDocentePlatformTemplateColumns: IColumn[] = [
    {
        type: 'text',
        width: '5rem',
        field: 'cTipoIdentId',
        header: 'Tipo de documento',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'cPersDocumento',
        header: 'Número de documento',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'nombreCompleto',
        header: 'Nombres',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'tbl_docente',
        header: 'Docente',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'tbl_docente_ie',
        header: 'Institución educativa',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'tbl_persona',
        header: 'Persona',
        text_header: 'center',
        text: 'center',
    },
]

export const estudiantePlatformTemplateColumns: IColumn[] = [
    {
        type: 'text',
        width: '5rem',
        field: 'iNivelGradoId',
        header: 'Grado',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'iSeccionId',
        header: 'Sección',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'cTipoIdentSigla',
        header: 'Tipo  de documento',
        text_header: 'center',
        text: 'center',

        inputType: 'dropdown',
        placeholder: 'Seleccione un tipo de documento',
        options: [
            { label: 'DNI', value: 'M' },
            { label: 'RUC', value: 'M' },
            { label: 'CDE', value: 'M' },
            { label: 'OTD', value: 'M' },
        ],
    },
    {
        type: 'text',
        width: '5rem',
        field: 'cPersDocumento',
        header: 'Numero de documento',
        text_header: 'center',
        text: 'center',
    },

    {
        type: 'text',
        width: '5rem',
        field: 'cEstCodigo',
        header: 'Codigo de estudiante',
        text_header: 'center',
        text: 'center',
    },

    {
        type: 'text',
        width: '5rem',
        field: 'cPersPaterno',
        header: 'Apellido paterno',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'cPersMaterno',
        header: 'Apellido materno',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'cPersNombre',
        header: 'Nombres',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'cPersSexo',
        header: 'Sexo',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'dPersNacimiento',
        header: 'Fecha de nacimiento',
        text_header: 'center',
        text: 'center',
    },
]

export const ambientesPlatformTemplateColumns: IColumn[] = [
    {
        type: 'text',
        width: '5rem',
        field: 'Turno',
        header: 'TURNO',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'Modalidad',
        header: 'MODALIDAD',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'dni_tutor',
        header: 'DNI',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'Grado',
        header: 'GRADO',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'Seccion',
        header: 'SECCIÓN',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'AmbienteArea',
        header: 'ÁREA',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'PisoAmbid',
        header: 'PISO',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'AmbienteNombre',
        header: 'NOMBRE',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'TipoAmbienteId',
        header: 'TIPO',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'EstadoAmbId',
        header: 'ESTADO',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'UbicaAmbId',
        header: 'UBICACIÓN',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'iUsoAmbId',
        header: 'USO',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'AmbienteAforo',
        header: 'AFORO',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'AmbienteObs',
        header: 'OBSERVACIÓN',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'AmbienteEstado',
        header: 'ESTADO',
        text_header: 'center',
        text: 'center',
    },
]

export const resultAmbientesPlatformTemplateColumns: IColumn[] = [
    {
        type: 'text',
        width: '5rem',
        field: 'AmbienteNombre',
        header: 'Nombre',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'ambiente',
        header: 'Ambiente',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'Grado_seccion',
        header: 'Grado y sección',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'configuracion',
        header: 'Configuración',
        text_header: 'center',
        text: 'center',
    },
]
