import { IColumn } from '@/app/shared/table-primeng/table-primeng.component'

export const ieTemplateSiagieColumns: IColumn[] = [
    {
        type: 'text',
        width: '5rem',
        field: 'CÓDIGO MODULAR',
        header: 'Item',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'INSTITUCIÓN EDUCATIVA',
        header: 'Item',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'MODALIDAD',
        header: 'Item',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'NIVEL',
        header: 'Item',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'TURNO',
        header: 'Item',
        text_header: 'center',
        text: 'center',
    },
]

export const estudianteTemplateSiagieColumns: IColumn[] = [
    {
        type: 'text',
        width: '5rem',
        field: 'ITEM',
        header: 'Item',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'GRADO',
        header: 'Grado',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'SECCIÓN',
        header: 'Sección',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'dTipoDocumento',
        header: 'Tipo de documento',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'iDocumento',
        header: 'Número de documento',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'reniec',
        header: 'Validado con reniec',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'iEstudianteCode',
        header: 'Código del estudiante',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'APELLIDO PATERNO',
        header: 'Apellido paterno',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'APELLIDO MATERNO',
        header: 'Apellidos materno',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'NOMBRES',
        header: 'Nombres',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'SEXO',
        header: 'Sexo',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'FECHA DE NACIMIENTO',
        header: 'Fecha de nacimiento',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'EDAD (AL 31 DE MARZO)',
        header: 'Edad (al 31 de marzo)',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'ESTADO DE MATRICULA',
        header: 'Estado de matricula',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'TIPO DE VACANTE',
        header: 'Tipo de vacante',
        text_header: 'center',
        text: 'center',
    },
]

export const resultEstudianteTemplateSiagieColumns: IColumn[] = [
    {
        type: 'item',
        width: '1rem',
        field: 'item',
        header: '',
        text_header: 'left',
        text: 'left',
    },
    {
        type: 'text',
        width: '10rem',
        field: 'persona_nomape',
        header: 'Estudiante',
        text_header: 'left',
        text: 'left',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'documento',
        header: 'Documento',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '6rem',
        field: 'codigo_estudiante',
        header: 'Codigo',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '6rem',
        field: 'grado_seccion',
        header: 'Grado y sección',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '3rem',
        field: 'persona_importado',
        header: 'Persona',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '3rem',
        field: 'estudiante_importado',
        header: 'Estudiante',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '3rem',
        field: 'matricula_importado',
        header: 'Matricula',
        text_header: 'center',
        text: 'center',
    },
]
