import { IColumn } from '@/app/shared/table-primeng/table-primeng.component'

export const headerTemplateSiagie: IColumn[] = [
    {
        type: 'text',
        width: '5rem',
        field: 'Item',
        header: 'CÓDIGO MODULAR',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'Item',
        header: 'INSTITUCIÓN EDUCATIVA',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'Item',
        header: 'MODALIDAD',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'Item',
        header: 'NIVEL',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'Item',
        header: 'TURNO',
        text_header: 'center',
        text: 'center',
    },
]

export const padresFamiliasTemplateColumns: IColumn[] = [
    {
        type: 'text',
        width: '5rem',
        field: 'Item',
        header: 'ITEM',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'Grado',
        header: 'GRADO',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'Sección',
        header: 'SECCIÓN',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'Tipo de documento',
        header: 'TIPO DE DOCUMENTO',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'Numero de documento',
        header: 'NÙMERO DE DOCUMENTO',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'Validado con reniec',
        header: 'VALIDADO CON RENIEC',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'Código del estudiante',
        header: 'CÓDIGO DEL ESTUDIANTE',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'Apellido paterno',
        header: 'APELLIDO PATERNO',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'Apellido materno',
        header: 'APELLIDO MATERNO',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'Nombres',
        header: 'NOMBRES',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'Sexo',
        header: 'SEXO',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'Fecha de nacimiento',
        header: 'FECHA DE NACIMIENTO',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'Edad al (31 de marzo)',
        header: 'EDAD AL (31 DE MARZO)',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'Estado de matricula',
        header: 'ESTADO DE MATRICULA',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'Apellidos y nombres',
        header: 'APELLIDOS Y NOMBRES',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'Padre Sexo',
        header: 'SEXO',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'Parentesco',
        header: 'PARENTESCO',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'Parentesco',
        header: 'TIPO DE DOCUMENTO',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'Parentesco',
        header: 'NÚMERO DE DOCUMENTO',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'Parentesco',
        header: 'VALIDADO CON RENIEC',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'Parentesco',
        header: 'CORREO ELECTRÓNICO',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'Parentesco',
        header: 'NÚMERO CELULAR',
        text_header: 'center',
        text: 'center',
    },
]

export const resultPadresFamiliasTemplateColumns: IColumn[] = []

export const estudianteTemplateSiagieColumns: IColumn[] = [
    {
        type: 'text',
        width: '5rem',
        field: 'ITEM',
        header: 'ITEM',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'GRADO',
        header: 'GRADO',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'SECCIÓN',
        header: 'SECCIÓN',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'dTipoDocumento',
        header: 'TIPO DE DOCUMENTO',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'iDocumento',
        header: 'NÚMERO DE DOCUMENTO',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'reniec',
        header: 'VALIDADO CON RENIEC',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'iEstudianteCode',
        header: 'CÓDIGO DEL ESTUDIANTE',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'APELLIDO PATERNO',
        header: 'APELLIDO PATERNO',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'APELLIDO MATERNO',
        header: 'APELLIDO MATERNO',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'NOMBRES',
        header: 'NOMBRES',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'SEXO',
        header: 'SEXO',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'FECHA DE NACIMIENTO',
        header: 'FECHA DE NACIMIENTO',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'EDAD (AL 31 DE MARZO)',
        header: 'EDAD (AL 31 DE MARZO)',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'ESTADO DE MATRICULA',
        header: 'ESTADO DE MATRICULA',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'TIPO DE VACANTE',
        header: 'TIPO DE VACANTE',
        text_header: 'center',
        text: 'center',
    },
]

export const resultEstudianteTemplateSiagieColumns: IColumn[] = [
    {
        type: 'item',
        width: '1rem',
        field: 'item',
        header: '',
        text_header: 'left',
        text: 'left',
    },
    {
        type: 'text',
        width: '10rem',
        field: 'persona_nomape',
        header: 'Estudiante',
        text_header: 'left',
        text: 'left',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'documento',
        header: 'Documento',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '6rem',
        field: 'codigo_estudiante',
        header: 'Codigo',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '6rem',
        field: 'grado_seccion',
        header: 'Grado y sección',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '3rem',
        field: 'persona_importado',
        header: 'Persona',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '3rem',
        field: 'estudiante_importado',
        header: 'Estudiante',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '3rem',
        field: 'matricula_importado',
        header: 'Matricula',
        text_header: 'center',
        text: 'center',
    },
]
