export const accesosAutorizadosColumns = [
    {
        type: 'text',
        width: '1rem',
        field: 'index',
        header: 'N°',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'cCredUsuario',
        header: 'Usuario',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'cNombre',
        header: 'Nombre',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'cIpCliente',
        header: 'IP pública',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'dtFecha',
        header: 'Fecha',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'cNavegador',
        header: 'Navegador',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'cDispositivo',
        header: 'Dispositivo',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'cSistmaOperativo',
        header: 'Sistema operativo',
        text_header: 'center',
        text: 'center',
    },
]

export const accesosFallidosColumns = [
    {
        type: 'text',
        width: '1rem',
        field: 'index',
        header: 'N°',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'cLogin',
        header: 'Usuario',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'cPassword',
        header: 'Contraseña',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'cMotivo',
        header: 'Mensaje del servidor',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'cIpCliente',
        header: 'IP cliente',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'dtFecha',
        header: 'Fecha',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'cNavegador',
        header: 'Navegador',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'cDispositivo',
        header: 'Dispositivo',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'cSistmaOperativo',
        header: 'Sistema operativo',
        text_header: 'center',
        text: 'center',
    },
]

export const auditoriaColumns = [
    {
        type: 'text',
        width: '1rem',
        field: 'index',
        header: 'N°',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'cAudUsuario',
        header: 'Usuario',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'cAudTipoOperaion',
        header: 'Operacion',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'dtFecha',
        header: 'Fecha',
        text_header: 'center',
        text: 'center',
    },
]

export const auditoriaMiddlewareColumns = [
    {
        type: 'text',
        width: '1rem',
        field: 'index',
        header: 'N°',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'cCredUsuario',
        header: 'Usuario',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'cAudTipoOperacion',
        header: 'Operacion',
        text_header: 'center',
        text: 'center',
    },
    {
        type: 'text',
        width: '5rem',
        field: 'dtFecha',
        header: 'Fecha',
        text_header: 'center',
        text: 'center',
    },
]
